version: '3.8'

services:
  blogging_service:
    container_name: blogging-service
    build: ../../.
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq-service
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  elasticsearch:
    container_name: elasticsearch-service
    image: "elasticsearch:7.17.6"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  consumer:
    container_name: consumer-service
    build: ../../.
    command: [ "python", "-m", "src.framework.consumers.consumer" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
